version: '3'

# create network so that another container can access it
networks:
  network-1:
    name: wida-network
    driver: bridge

services:
  postgres:
    container_name: wid-pg-db
    image: postgres:latest
    environment:
      POSTGRES_DB: wida
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    networks:
      - network-1
    volumes:
      - ./initPg.sql:/docker-entrypoint-initdb.d/initPg.sql


